# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokfresh < Formula
  desc "Automate your Claude token reset timing via Cloudflare Workers"
  homepage "https://github.com/stevejkang/tokfresh-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.1/tokfresh_0.0.1_darwin_amd64.tar.gz"
      sha256 "7e9aad3d652745cae2948411ba7df16593371c99d4a91e163fd10fec156b23da"

      define_method(:install) do
        bin.install "tokfresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.1/tokfresh_0.0.1_darwin_arm64.tar.gz"
      sha256 "ad0db4f24bd321bb191e0ef3c884c5d3a1ba658d32fce201b72a6f909ee6c6fd"

      define_method(:install) do
        bin.install "tokfresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.1/tokfresh_0.0.1_linux_amd64.tar.gz"
      sha256 "8ce4252dbbe2215b6944fe3311b876fde2a3b3324edc61b53fbb1cb8c3769913"
      define_method(:install) do
        bin.install "tokfresh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.1/tokfresh_0.0.1_linux_arm64.tar.gz"
      sha256 "a0c0f84af60e96f66bf9209e91f9bdee3dfb9e24e9283cd7ae2de8f3b4f7d112"
      define_method(:install) do
        bin.install "tokfresh"
      end
    end
  end

  test do
    system "#{bin}/tokfresh", "version"
  end
end
