# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokfresh < Formula
  desc "Automate your Claude token reset timing via Cloudflare Workers"
  homepage "https://github.com/stevejkang/tokfresh-cli"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.3/tokfresh_0.0.3_darwin_amd64.tar.gz"
      sha256 "6e5ddfc60f0cac43f75a226da89962fd527b96f70fa4fcd8e40d2bed64d9f713"

      define_method(:install) do
        bin.install "tokfresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.3/tokfresh_0.0.3_darwin_arm64.tar.gz"
      sha256 "cae0b33dd771f271161cf8ef220cf63698f4e1209d60e49cd8f113578c51ab6a"

      define_method(:install) do
        bin.install "tokfresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.3/tokfresh_0.0.3_linux_amd64.tar.gz"
      sha256 "9edf4a4e78175a8653c614d1fda5e7cc95f7141beab85c9a19c7a6bea05c5266"
      define_method(:install) do
        bin.install "tokfresh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.3/tokfresh_0.0.3_linux_arm64.tar.gz"
      sha256 "e299125a1b3e3617bf46f22ec35893d448cd89eea979007d4b921aec03c1bc7c"
      define_method(:install) do
        bin.install "tokfresh"
      end
    end
  end

  test do
    system "#{bin}/tokfresh", "version"
  end
end
