# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokfresh < Formula
  desc "Automate your Claude token reset timing via Cloudflare Workers"
  homepage "https://github.com/stevejkang/tokfresh-cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.2/tokfresh_0.0.2_darwin_amd64.tar.gz"
      sha256 "79faa978e3e41c74b4243ff0d6c7b371cdf993352a114a34018f9928f81da4b8"

      define_method(:install) do
        bin.install "tokfresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.2/tokfresh_0.0.2_darwin_arm64.tar.gz"
      sha256 "2229e88cd32eac7c83dbb3cf62b3534f0de099f675a2115e46134319c67c1d81"

      define_method(:install) do
        bin.install "tokfresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.2/tokfresh_0.0.2_linux_amd64.tar.gz"
      sha256 "44e5272097e4d0f13472512099203cad8677b8a3856da0ed3c1b2d5649455dce"
      define_method(:install) do
        bin.install "tokfresh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevejkang/tokfresh-cli/releases/download/v0.0.2/tokfresh_0.0.2_linux_arm64.tar.gz"
      sha256 "03d0e60a8053853c48a3e898c7434cb5a2bb6c2f8a91d51712cf57c68936da34"
      define_method(:install) do
        bin.install "tokfresh"
      end
    end
  end

  test do
    system "#{bin}/tokfresh", "version"
  end
end
